# Generated by Django 5.2.11 on 2026-02-16 12:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('position', models.CharField(choices=[('NONE', 'None'), ('LONG', 'Long')], default='NONE', max_length=10)),
                ('last_signal', models.CharField(default='NONE', max_length=10)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='StockConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_token', models.CharField(help_text='SmartAPI symbol token (e.g. 2885 for RELIANCE)', max_length=20)),
                ('trading_symbol', models.CharField(help_text='SmartAPI trading symbol (e.g. RELIANCE-EQ)', max_length=50)),
                ('exchange', models.CharField(help_text='Exchange name (e.g. NSE)', max_length=20)),
                ('timeframe', models.CharField(help_text='SmartAPI interval (e.g. ONE_MINUTE)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('symbol_token', 'exchange', 'timeframe')},
            },
        ),
        migrations.CreateModel(
            name='SignalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL'), ('NO SIGNAL', 'NO SIGNAL')], max_length=15)),
                ('crossover_timestamp', models.DateTimeField()),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.FloatField()),
                ('ema_short', models.FloatField()),
                ('ema_long', models.FloatField()),
                ('diff', models.FloatField()),
                ('executed', models.BooleanField(default=False)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.stockconfig')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_span', models.IntegerField(default=9)),
                ('long_span', models.IntegerField(default=21)),
                ('candle_count', models.IntegerField(default=100)),
                ('signal_validity_minutes', models.IntegerField(default=5, help_text='Signal must be executed within this many minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strategy', to='trading.stockconfig')),
            ],
        ),
    ]
