# Generated by Django 5.2.11 on 2026-02-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Stock ticker symbol, e.g. AAPL, INFY', max_length=20)),
                ('exchange', models.CharField(help_text='Exchange name, e.g. NSE, BSE, NASDAQ', max_length=20)),
                ('timeframe', models.CharField(help_text='Timeframe for candles, e.g. 1m, 5m, 1h, 1d', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this stock configuration is active for use')),
            ],
            options={
                'unique_together': {('symbol', 'exchange', 'timeframe')},
            },
        ),
    ]
