# Generated by Django 5.2.11 on 2026-02-19 11:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('broker_status', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField()),
                ('order_type', models.CharField(default='MARKET', max_length=20)),
                ('broker_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trading.signallog')),
            ],
        ),
    ]
