# Generated by Django 5.2.11 on 2026-02-11 12:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('position', models.CharField(choices=[('NONE', 'None'), ('LONG', 'Long'), ('SHORT', 'Short')], default='NONE', max_length=10)),
                ('last_signal', models.CharField(default='NONE', max_length=10)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
