# Generated by Django 5.2.11 on 2026-02-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_tradestate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockconfig',
            name='exchange',
            field=models.CharField(help_text='Exchange name (e.g. NSE)', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockconfig',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Enable/Disable this stock for live trading'),
        ),
        migrations.AlterField(
            model_name='stockconfig',
            name='symbol',
            field=models.CharField(help_text='SmartAPI symbol token (e.g. 3045 for RELIANCE)', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockconfig',
            name='timeframe',
            field=models.CharField(help_text='SmartAPI interval (e.g. ONE_MINUTE)', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradestate',
            name='position',
            field=models.CharField(choices=[('NONE', 'None'), ('LONG', 'Long')], default='NONE', max_length=10),
        ),
    ]
