# Generated by Django 5.2.11 on 2026-02-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_orderlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signallog',
            name='executed',
        ),
        migrations.AddField(
            model_name='signallog',
            name='execution_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SKIPPED', 'Skipped'), ('ATTEMPTED', 'Attempted'), ('EXECUTED', 'Executed'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
