# Generated by Django 5.2.11 on 2026-02-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_alter_stockconfig_exchange_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockconfig',
            old_name='symbol',
            new_name='symbol_token',
        ),
        migrations.AlterUniqueTogether(
            name='stockconfig',
            unique_together={('symbol_token', 'exchange', 'timeframe')},
        ),
        migrations.AddField(
            model_name='stockconfig',
            name='trading_symbol',
            field=models.CharField(default='RELIANCE-EQ', help_text='SmartAPI trading symbol (e.g. RELIANCE-EQ)', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockconfig',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Enable/Disable this stock for trading'),
        ),
    ]
