# Generated by Django 5.2.11 on 2026-02-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionchainsnapshot',
            name='is_day_baseline',
            field=models.BooleanField(default=False),
        ),
    ]
